[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 200
via_ir = true

[fuzz]
runs = 1000

[invariant]
runs = 256
depth = 50
fail_on_revert = false
